language: julia

os:
  - osx

env:
  CODECOV_TOKEN="b2c21562-0860-4b9a-9971-bd287afb499f"

codecov: true

julia:
  - 1.0
  - 1.4
  - 1.5
  - nightly


notifications:
   email:
     - ctk@ncsu.edu

after_success:
   - julia -e 'cd(Pkg.dir("SIAMFANLEquations.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: osx 
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
      
