language: julia

os:
  - osx

env:
  CODECOV_TOKEN="b2c21562-0860-4b9a-9971-bd287afb499f"

codecov: true

julia:
  - 1.5
  - nightly


notifications:
   email:
     - ctk@ncsu.edu

after_success:
   - julia -e 'cd(Pkg.dir("SIAMFANLEquations.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly
