name = "SIAMFANLEquations"
uuid = "084e46ad-d928-497d-ad5e-07fa361a48c4"
authors = ["C. T. (Tim) Kelley <tim_kelley@ncsu.edu>"]
version = "0.1.5"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
